// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteMvcArthur.Data;

namespace TesteMvcArthur.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220127124744_Initi")]
    partial class Initi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TesteMvcArthur.Models.FilhosModel", b =>
                {
                    b.Property<int>("FilhoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionariosFuncionarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FilhoId");

                    b.HasIndex("FuncionariosFuncionarioId");

                    b.ToTable("Filhos");
                });

            modelBuilder.Entity("TesteMvcArthur.Models.FuncionariosModel", b =>
                {
                    b.Property<int>("FuncionarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("FuncionarioId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("TesteMvcArthur.Models.FilhosModel", b =>
                {
                    b.HasOne("TesteMvcArthur.Models.FuncionariosModel", "Funcionarios")
                        .WithMany()
                        .HasForeignKey("FuncionariosFuncionarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
